### ISSUE TITLE
error loading kubeconfig: no Auth Provider found for name "***"

### ISSUE THREAD

**Issue by IgorGov** [teamcode-inc/kubeorbit#7]
kubectl is working fine and all other cli tools which uses the kubeconfig from the default location ($HOME/.kube/config) are working for me

**Comment by ericjee** [comment]
Hi @IgorGov, Thx for trying out! I think I forget to import the client auth plugin for CLI, I just pushed a new commit to the `bugfix/auth-plugin` branch, Do you have time to help verify it?

**Comment by IgorGov** [comment]
how can i verify it?

**Comment by ericjee** [comment]
[orbitctl-darwin.zip](https://github.com/teamcode-inc/kubeorbit/files/8140054/orbitctl-darwin.zip)
Try this one @IgorGov

**Comment by IgorGov** [comment]
`orbitctl -h` - seems to work now
